apiVersion: v1
kind: Service
metadata:
  name: example-books-service-mongo
  namespace: course-kubernetes
spec:
  type: NodePort
  selector:
    app: example-books-service-mongo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30001