apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-books-service-mongo
  namespace: course-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-books-service-mongo
  template:
    metadata:
      labels:
        app: example-books-service-mongo
    spec:
      containers:
        - name: example-books-microservice-mongo
          image: example-books-microservice-mongo:1.0.0
          imagePullPolicy: Never
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
          ports:
            - containerPort: 3000
